### ISSUE TITLE
Links for Items "ECDSA" and "Cryptographic Hash Function" are the same

### ISSUE THREAD

**Issue by JonathanScialpi** [benstew/blockchain-for-software-engineers#3]
When I got up to the "ECDSA" item of the list I noticed that it had the same link as "Cryptographic Hash Function". I think the link to ECDSA is the one that needs to be updated

**Comment by patnealcodes** [comment]
Yep. I believe the correct link for ECDSA should be https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm.

Is this correct, @benstew , or am I learning the wrong thing? :D

**Comment by benstew** [comment]
That is correct! Will update that link.

Thanks @JonathanScialpi @patnealcodes for pointing out.

**Comment by benstew** [comment]
Finally updated :)
